# Generated by Django 2.2.5 on 2020-01-04 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import telegram_bot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('knowledge_code', models.CharField(default=telegram_bot.models.md5_func, max_length=32, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('modify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_unlike', models.CharField(blank=True, default='so_so', max_length=10, null=True)),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.Knowledge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('score', models.IntegerField(default=0)),
                ('policy_code', models.CharField(default=telegram_bot.models.md5_func, max_length=32, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('modify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_unlike', models.CharField(blank=True, default='so_so', max_length=10, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.Policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('knowledge_pack', models.ManyToManyField(blank=True, null=True, to='telegram_bot.KnowledgeStatus')),
                ('policy_pack', models.ManyToManyField(blank=True, null=True, to='telegram_bot.PolicyStatus')),
            ],
        ),
    ]
